### ISSUE TITLE
[Bugs] 1.19.2 and backport bugs

### ISSUE THREAD

**Issue by ut-64bit** [Spartan80/Old-guns#10]
- Animation speed is very fast.
- Reloading speed is very fast.
- Very short interval before the next bullet can be struck.
- Can't change settings in config?
- The gun barrel can be taken out from the GUI of the attachment.
- After removing the barrel of the gun, when I open the GUI again, the barrel is back to where it was.
- The magazine can be stacked.
- Cannot load magazine with R key.

**Comment by Spartan80** [comment]
Wow I'll check it out, thanks for commenting
わあ、調べてみます、コメントありがとうございます

**Comment by ut-64bit** [comment]
Recoil seems to be gone.

**Comment by Wyvern500** [comment]
Are you talking about camera recoil?
カメラの反動のことを言ってるの？

**Comment by ut-64bit** [comment]
Yes. It was in an older version, but was it removed?

**Comment by Wyvern500** [comment]
Yes, would you like me to add it?
はい、もう一度追加してもよろしいでしょうか？

**Comment by ut-64bit** [comment]
Yes please.
But maybe some people prefer no recoil, so it would be nice to be able to set it in config.

Sorry for the late reply as I have been busy these days.

**Comment by Wyvern500** [comment]
Ok, don't worry, I'll start working on it.
わかりました、心配しないでください、作業を始めます。

**Comment by ut-64bit** [comment]
Please correct this as well.
https://github.com/Spartan80/Old-guns/issues/11
