### ISSUE TITLE
[Bug] Bugs I found during my survival.

### ISSUE THREAD

**Issue by ut-64bit** [Spartan80/Old-guns#11]
When pressing the button to create a gun without selecting a gun in the Gun Crafting Block, the game crashes.

![2023-08-08_14 22 11_edited_2](https://github.com/Spartan80/Old-guns/assets/83690503/d9d18c2a-0309-40b5-8e62-28544da17f66)

**Comment by ut-64bit** [comment]
I found another bug, although not the one mentioned in the title.
Bullets can be made without consuming gunpowder.

**Comment by Wyvern500** [comment]
Dude, thank you very much, you are helping me a lot, I will fix it and also try to improve the feeling when you are shooting, but don't expect that much
おい、どうもありがとう、あなたは私を大いに助けてくれます。私はそれを修正し、射撃時の感覚を改善するように努めますが、あまり期待しないでください。

**Comment by Wyvern500** [comment]
Another thing is that i'll experiment with 3rd person rendering, so maybe you will see how the player holds the gun as a gun and not as a simple item, and also, if is it possible when you aim, the player in 3rd person will aim too
もう 1 つは、三人称レンダリングを実験するつもりです。そのため、プレイヤーが武器を単なるオブジェクトではなく武器のように保持している様子がわかるでしょう。また、可能であれば、狙いを定めたときに三人称プレイヤーも見えるでしょう。も狙うだろう

**Comment by Wyvern500** [comment]
You gave me motivation, I will redo all the graphical interfaces and check what I can improve
君のおかげでやる気が出たよ。すべてのグラフィカル・インターフェースをやり直して、改善できる点をチェックするつもりだ。
