### ISSUE TITLE
"No model provided"

### ISSUE THREAD

**Issue by RyanDavanzo** [Spartan80/Old-guns#4]
The mod works, but the guns are all invisible and it says "no model provided" on chat. Is it an error or I'm just dumb? ;w;

**Comment by Spartan80** [comment]
show me a screenshot or the steps to reproduce the bug

**Comment by RyanDavanzo** [comment]
![image](https://user-images.githubusercontent.com/85040318/173940633-8333eb91-d435-47ef-b92a-42be0d7faa87.png)

Just pick the item, put it on the hotbar and select it.

**Comment by Spartan80** [comment]
which version of minecraft is it?

**Comment by RyanDavanzo** [comment]
1.16.5

**Comment by Spartan80** [comment]
let me check

**Comment by RyanDavanzo** [comment]
![image](https://user-images.githubusercontent.com/85040318/173941350-07d91230-5e8e-4839-9e35-8960204dc8da.png)

Weirdly enough is that MrCrayfish's Gun Mod is also having the invisible stuff bug lol

**Comment by RyanDavanzo** [comment]
But I tried with it disabled, so yeah

**Comment by Spartan80** [comment]
i think the bug is fixed

**Comment by RyanDavanzo** [comment]
so there's a new version to download?

**Comment by Spartan80** [comment]
OldGuns 1.0.2.1, i'm uploading it

**Comment by RyanDavanzo** [comment]
alrighty :3

**Comment by Spartan80** [comment]
:3

**Comment by Spartan80** [comment]
check the new version, it's already approved

**Comment by RyanDavanzo** [comment]
Nope...same thing ;w;

**Comment by Spartan80** [comment]
shit

**Comment by RyanDavanzo** [comment]
let me try to change some configs

**Comment by Spartan80** [comment]
I know what causes the bug, but i don't know why

**Comment by RyanDavanzo** [comment]
what causes it?

**Comment by Spartan80** [comment]
I think an event where I register the gun models doesn't fire and I don't know why

**Comment by RyanDavanzo** [comment]
oh man...i know the feeling
i use Unity ;w;
i know this might be boring, but try to delete and rewrite the code you use to fire the models.
works for me most of the time

**Comment by Spartan80** [comment]
![2022-06-15_16 57 47](https://user-images.githubusercontent.com/52138714/173955953-e2a20fd0-292d-447f-8b53-eeef5f7614d9.png)
Look, it works for me, rewriting the code won't fix anything.
![code](https://user-images.githubusercontent.com/52138714/173956147-ca3f93fb-9507-4623-a6a7-9db1fcef1040.JPG)
This is where i post the event

**Comment by RyanDavanzo** [comment]
I already tried to run the mod alone, but the same thing happens. i'll try to reinstall the game

**Comment by Spartan80** [comment]
im srry man, i dont know what to do

**Comment by RyanDavanzo** [comment]
hey, it's ok
it's not your fault
my pc is getting weird those days. maybe it even isnt the game itself
