### ISSUE TITLE
JEI does not show gun recipes.

### ISSUE THREAD

**Issue by ut-64bit** [Spartan80/Old-guns#6]
This text was translated from Japanese using DeepL.

**Comment by Spartan80** [comment]
> This text was translated from Japanese using DeepL.

Sorry, I don't plan to add the recipes to JEI, you just need the tables for most recipes

**Comment by Spartan80** [comment]
申し訳ありませんが、JEI にレシピを追加するつもりはありません。ほとんどのレシピのテーブルが必要なだけです。これが正しく書かれていることを願っています
