### ISSUE TITLE
[Proposal] Ensure that magazines with the highest number of rounds remaining are used first.

### ISSUE THREAD

**Issue by ut-64bit** [Spartan80/Old-guns#7]

**Comment by Spartan80** [comment]
I think is a good idea, thank you for commenting, i'll add it soon
良いアイデアだと思います、コメントありがとうございます、すぐに追加します、もう一度これが正しく書かれていることを願っています

**Comment by Spartan80** [comment]
By the way, what version are you playing?
ちなみに、どのバージョンでプレイしてますか？

**Comment by ut-64bit** [comment]
I am playing with version 1.18.2.

And I have one more suggestion.
Is it possible to remove the magazine with the "u" key?
Sorry if there is already such a feature.

**Comment by Wyvern500** [comment]
Oh, it's already added, by the way, would you like me to do a backport from 1.19.2 to 1.18.2?, there are more guns and a better animation system
あ、もう追加されてますね。 ところで、1.19.2 を 1.18.2 にバックポートしますか? より多くの武器とより優れたアニメーションシステムを備えています。

**Comment by ut-64bit** [comment]
I would love to see it back ported!

**Comment by Wyvern500** [comment]
Ok, wait for it, I'll also fix some bugs.
はい、お待ちください。 いくつかのバグも修正されています。

**Comment by Wyvern500** [comment]
The improvement has been added on the last mod file, so give it a try.
最新のMODファイルでは改良が加えられているので、ぜひ試してみてください。
