### ISSUE TITLE
[Bug] It is possible to pack bullets beyond the limit.

### ISSUE THREAD

**Issue by ut-64bit** [Spartan80/Old-guns#8]
Version: 1.18.2
How to reproduce:
1. prepare a gun that uses bullets directly for reloading, such as Kar98k.
2. reload normally.
- At this stage, you should see something like "5 / 5".
3. Press the reload key to reload further.
- Continue loading bullets into the gun until there are no more bullets in the inventory.
4. guns that have been reloaded beyond their limit will no longer be able to fire in survival mode.

This text was translated using DeepL.

**Comment by Wyvern500** [comment]
Thank you for commeting, i'll check it out later
コメントありがとうございます、後で確認してみます。

**Comment by Wyvern500** [comment]
The bug has been fixed and we ported it to 1.18.2, so give it a try.
バグは修正され 1.18.2 に移植されましたので、ぜひお試しください。
